- name: print locally
  hosts: localhost
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: "Hello World"
    - name: print task2
      ansible.builtin.debug:
        msg: "This is task 2"
